on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

name: Latest Release

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: Lint files
    runs-on: ['self-hosted', 'Linux', 'X64']
    steps:
      - name: Install dependencies
        run: sudo apt update && sudo apt install libsnmp-dev build-essential -y
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: latest
  build:
    runs-on: ['self-hosted', 'Linux', 'X64']
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.17.x'
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test
  release-linux-amd64:
    needs: build
    name: release linux/amd64
    runs-on: ['self-hosted', 'Linux', 'X64']
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: linux
          goarch: amd64